=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Framework.12.750.1/runtimes/native1.12-tchmi/Schema/FrameworkDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "version": {
            "type": "object",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "integer",
                    "minimum": 0
                },
                "minor": {
                    "type": "integer",
                    "minimum": 0
                },
                "revision": {
                    "type": "integer",
                    "minimum": 0
                },
                "build": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "required": [
                "full",
                "major",
                "minor",
                "revision",
                "build"
            ]
        },
        "dependencyFiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Path to the file",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "Stylesheet",
                            "JavaScript"
                        ],
                        "description": "Type of the framework asset."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "required": [
                    "name",
                    "type",
                    "description"
                ]
            }
        },
        "events": {
            "type": "array",
            "description": "A list of events assoziated to the framework.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Internal name of the event."
                    },
                    "displayName": {
                        "type": "string",
                        "description": "Name which should be presented the user."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this event."
                    },
                    "category": {
                        "type": "string",
                        "enum": [
                            "Framework"
                        ],
                        "description": ""
                    },
                    "allowsPreventDefault": {
                        "type": "boolean",
                        "description": "The event can have the option preventDefault."
                    }
                },
                "required": [
                    "name",
                    "displayName",
                    "description"
                ]
            }
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "required": [
                    "schema"
                ]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the framework core.",
            "additionalProperties": {
                "type": "string",
                "description": "Definition of Language and Region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US')."
            }
        }
    },
    "required": [
        "version",
        "dependencyFiles",
        "events",
        "dataTypes"
    ]
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Framework.12.750.1/runtimes/native1.12-tchmi/Description.json
{
    "$schema": "../TcHmiFramework/Schema/FrameworkDescription.Schema.json",
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "Object.js",
            "type": "JavaScript",
            "description": "Inheritance and other helper functions."
        },
        {
            "name": "Lib/jquery.min.js",
            "type": "JavaScript",
            "description": "jQuery library"
        },
        {
            "name": "Lib/acorn.js",
            "type": "JavaScript",
            "description": ""
        },
        {
            "name": "Style.css",
            "type": "Stylesheet",
            "description": ""
        },
        {
            "name": "TcHmiFramework.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "events": [
        {
            "name": "onInitialized",
            "displayName": "onInitialized",
            "category": "Framework",
            "description": "This event is fired after the framework is initialized. Controls and Symbols are not yet initialized at this time."
        },
        {
            "name": "onLocaleChanged",
            "displayName": "onLocaleChanged",
            "category": "Framework",
            "description": "This event is fired after a (perhaps new) locale has been loaded."
        },
        {
            "name": "onThemeDataChanged",
            "displayName": "onThemeDataChanged",
            "category": "Framework",
            "description": "This event is fired after the theme json and all css files have been loaded at a theme change. It is additionally fired when a new font-face file has been fetched."
        },
        {
            "name": "onUserChanged",
            "displayName": "onUserChanged",
            "category": "Framework",
            "description": "This event is fired, if a new user is logged in."
        },
        {
            "name": "onUserDataChanged",
            "displayName": "onUserDataChanged",
            "category": "Framework",
            "description": "This event is fired, if a new user is logged in or the user configuration (group membership, timezone...) of the logged in user has changed."
        },
        {
            "name": "onUserInGroupChanged",
            "displayName": "onUserInGroupChanged",
            "category": "Framework",
            "description": "This event is fired after a user is known to be in different usergroups or no authentification is required."
        },
        {
            "name": "onConfigChanged",
            "displayName": "onConfigChanged",
            "category": "Framework",
            "description": "This event is fired when the tchmiconfig.json has changed. This file can only change while engineering."
        }
    ],
    "dataTypes": [
        {
            "schema": "Schema/Types.Schema.json"
        }
    ],
    "languages": {
        "en": "Lang/en.json",
        "de": "Lang/de.json"
    }
}
