=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Framework.12.750.1/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "full",
                "major",
                "minor",
                "revision",
                "build"
            ]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the file",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "Stylesheet",
                            "JavaScript"
                        ],
                        "description": "Type of the function asset."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "type",
                    "description"
                ]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": [
                        "Synchronous",
                        "Asynchronous"
                    ]
                },
                "returnValue": {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            }
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function"
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Type from argument."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "name",
                            "displayName",
                            "description",
                            "type",
                            "required",
                            "bindable"
                        ]
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "displayName",
                "namespace",
                "description",
                "arguments",
                "returnValue"
            ]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "schema"
                ]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "type": "string",
                "description": "Definition of Language and Region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US')."
            }
        }
    },
    "required": [
        "function"
    ]
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/Log.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "Log.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Log",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Log",
        "visible": true,
        "category": "Diagnostics",
        "waitMode": "Synchronous",
        "injectContextObject": false,
        "description": "Logs a message to the browser console.",
        "returnValue": null,
        "arguments": [
            {
                "name": "level",
                "displayName": "level",
                "type": "tchmi:framework#/definitions/TcHmi.Functions.Beckhoff.Log.Level",
                "description": "The log level.",
                "defaultValue": "Debug",
                "required": true,
                "bindable": true
            },
            {
                "name": "message",
                "displayName": "message",
                "type": "tchmi:general#/definitions/String",
                "description": "The log message.",
                "defaultValue": "",
                "required": true,
                "bindable": true
            },
            {
                "name": "optionalParameters",
                "displayName": "optionalParameters",
                "type": "tchmi:general#/definitions/Any",
                "description": "Optional parameters of underlying browser log function.",
                "defaultValue": "",
                "restParameter": true,
                "required": false,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/GetElementByIndex.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "GetElementByIndex.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GetElementByIndex",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GetElementByIndex",
        "visible": true,
        "description": "Return the value at the array index position.",
        "category": "Data Conversion",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "arraySymbol",
                "displayName": "arraySymbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "Value to be trimmed",
                "required": true,
                "bindable": true
            },
            {
                "name": "index",
                "displayName": "index",
                "type": "tchmi:framework#/definitions/PositiveNumber",
                "description": "Index",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/SetTheme.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "SetTheme.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetTheme",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetTheme",
        "description": "Set a new Theme.",
        "category": "Theme",
        "returnValue": null,
        "arguments": [
            {
                "name": "newTheme",
                "displayName": "newTheme",
                "type": "tchmi:framework#/definitions/ThemeName",
                "description": "New theme name.",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/FormatString.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "FormatString.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "FormatString",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "FormatString",
        "visible": true,
        "description": "Format a string. Placeholder syntax in format string: '{' to begin placeholder, optional parameter-index with | as seperator, description and '}' to close the placeholder. Example: {0|.1f}",
        "category": "Formatting",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "formatString",
                "displayName": "formatString",
                "type": "tchmi:general#/definitions/String",
                "description": "FormatString with placeholder to be formatted",
                "required": true,
                "bindable": true
            },
            {
                "name": "args",
                "displayName": "args",
                "type": "tchmi:general#/definitions/Any",
                "description": "Argument to format the placeholder in formatString",
                "required": true,
                "bindable": true,
                "restParameter": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/LineChartTooltipFormatter.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "LineChartTooltipFormatter.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "LineChartTooltipFormatter",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "LineChartTooltipFormatter",
        "visible": false,
        "description": "Return a formatted string for the tooltip passed in.",
        "category": "Formatting",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "xValue",
                "displayName": "xValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "The xValue to format.",
                "required": true,
                "bindable": true
            },
            {
                "name": "yValue",
                "displayName": "yValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "The yValue to format.",
                "required": true,
                "bindable": true
            },
            {
                "name": "xShow",
                "displayName": "xShow",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "Shows the xValue to format.",
                "required": false,
                "bindable": true,
                "defaultValue": true
            },
            {
                "name": "yShow",
                "displayName": "yShow",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "Shows the yValue to format.",
                "required": false,
                "bindable": true,
                "defaultValue": true
            },
            {
                "name": "xMaxDecimals",
                "displayName": "xMaxDecimals",
                "type": "tchmi:general#/definitions/Number",
                "description": "How many decimal places the xValue should have.",
                "required": false,
                "bindable": true
            },
            {
                "name": "yMaxDecimals",
                "displayName": "yMaxDecimals",
                "type": "tchmi:general#/definitions/Number",
                "description": "How many decimal places the yValue should have.",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": []
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/SetLocaleEx.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "SetLocaleEx.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetLocaleEx",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetLocaleEx",
        "visible": true,
        "category": "Locale",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Sets the application locale. The function waits for loading of the language files.",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "defaultValue": null,
                "required": true,
                "bindable": false
            },
            {
                "name": "locale",
                "displayName": "locale",
                "type": "tchmi:general#/definitions/ProjectLocale",
                "description": "Locale",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/ForceLogout.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "ForceLogout.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ForceLogout",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ForceLogout",
        "visible": true,
        "category": "UserManagement",
        "description": "Logout a different user or all from a TcHmiServer.\nThis function is deprecated. Its recommended to use ForceLogoutEx.",
        "returnValue": {
            "type": "tchmi:general#/definitions/Boolean",
            "description": "Returns a boolean if the logout was called."
        },
        "arguments": [
            {
                "name": "username",
                "displayName": "username",
                "type": "tchmi:general#/definitions/String",
                "description": "Username to logout. Logout all users if left empty.",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/ToUpperCase.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "ToUpperCase.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ToUpperCase",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ToUpperCase",
        "visible": true,
        "description": "Convert string value to uppercase.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/String",
                "description": "Value to uppercase",
                "required": true,
                "bindable": true
            }
        ]
    }
}
