=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Framework.12.750.1/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "full",
                "major",
                "minor",
                "revision",
                "build"
            ]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the file",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "Stylesheet",
                            "JavaScript"
                        ],
                        "description": "Type of the function asset."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "type",
                    "description"
                ]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": [
                        "Synchronous",
                        "Asynchronous"
                    ]
                },
                "returnValue": {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            }
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function"
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Type from argument."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "name",
                            "displayName",
                            "description",
                            "type",
                            "required",
                            "bindable"
                        ]
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "displayName",
                "namespace",
                "description",
                "arguments",
                "returnValue"
            ]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "schema"
                ]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "type": "string",
                "description": "Definition of Language and Region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US')."
            }
        }
    },
    "required": [
        "function"
    ]
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/ForceLogoutEx.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "ForceLogoutEx.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ForceLogoutEx",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ForceLogoutEx",
        "visible": true,
        "category": "UserManagement",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Logout a different user or all from a TcHmiServer",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "defaultValue": null,
                "required": true,
                "bindable": false
            },
            {
                "name": "username",
                "displayName": "username",
                "type": "tchmi:general#/definitions/String",
                "description": "Username to logout. Logout all users if left empty.",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/GoToLoginPage.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "GoToLoginPage.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GoToLoginPage",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GoToLoginPage",
        "visible": true,
        "category": "UserManagement",
        "description": "Replace the current view with the login page",
        "returnValue": {
            "type": "tchmi:general#/definitions/Boolean",
            "description": "Returns a boolean if the page change was called."
        },
        "arguments": []
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/TeachRecipe.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "TeachRecipe.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "TeachRecipe",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "TeachRecipe",
        "visible": true,
        "category": "Recipe",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Reads the current values which are referenced from a base recipe and write it into the same recipe.",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "defaultValue": null,
                "required": true,
                "bindable": false
            },
            {
                "name": "recipeReference",
                "displayName": "recipeReference",
                "type": "tchmi:framework#/definitions/RecipeReference",
                "description": "Reference (path + '::' + name) of the recipe",
                "defaultValue": "",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/RemoveBinding.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "RemoveBinding.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "RemoveBinding",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "RemoveBinding",
        "description": "Removes a binding between a symbol and a control attribute setter function by name of property.",
        "category": "Binding",
        "returnValue": null,
        "arguments": [
            {
                "name": "control",
                "displayName": "control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "propertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "The target attribute property name of control.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/GetRegisteredLocales.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "GetRegisteredLocales.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GetRegisteredLocales",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GetRegisteredLocales",
        "visible": true,
        "category": "Locale",
        "description": "Returns the list of registered locales as array of string.",
        "returnValue": {
            "type": "tchmi:general#/definitions/Array"
        },
        "arguments": []
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/SetAttributeToThemeValue.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "SetAttributeToThemeValue.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetAttributeToThemeValue",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetAttributeToThemeValue",
        "description": "Sets the default value of a property and change it (if needed) on theme change.",
        "category": "Theme",
        "returnValue": null,
        "arguments": [
            {
                "name": "control",
                "displayName": "control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control to set the default value on it.",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "propertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "Name of the property to set default.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/SetLocale.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "SetLocale.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetLocale",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetLocale",
        "visible": true,
        "category": "Locale",
        "description": "Sets the application locale.\nThis function is deprecated. Its recommended to use SetLocaleEx which waits for loading of the language files.",
        "returnValue": null,
        "arguments": [
            {
                "name": "locale",
                "displayName": "locale",
                "type": "tchmi:general#/definitions/ProjectLocale",
                "description": "Locale",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/Increment.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "Increment.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Increment",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Increment",
        "visible": true,
        "description": "Increment a binding value.",
        "category": "Data Conversion",
        "injectContextObject": true,
        "waitMode": "Asynchronous",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "value",
                "displayName": "value",
                "type": "tchmi:framework#/definitions/TcHmi.Functions.Beckhoff.Increment.IncrementValueSymbol",
                "description": "Value to be incremented",
                "required": true,
                "bindable": true
            },
            {
                "name": "maxValue",
                "displayName": "maxValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "Maximum value(inclusive) to which the symbol will incremented",
                "required": false,
                "bindable": true
            },
            {
                "name": "stepWidth",
                "displayName": "stepWidth",
                "type": "tchmi:general#/definitions/Number",
                "description": "Used stepwidth for increment",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": [
        {
            "schema": "Schema/Types.Schema.json"
        }
    ]
}
