=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Framework.12.750.1/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "full",
                "major",
                "minor",
                "revision",
                "build"
            ]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the file",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "Stylesheet",
                            "JavaScript"
                        ],
                        "description": "Type of the function asset."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "type",
                    "description"
                ]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": [
                        "Synchronous",
                        "Asynchronous"
                    ]
                },
                "returnValue": {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            }
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function"
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Type from argument."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "name",
                            "displayName",
                            "description",
                            "type",
                            "required",
                            "bindable"
                        ]
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "displayName",
                "namespace",
                "description",
                "arguments",
                "returnValue"
            ]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(\/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": [
                    "schema"
                ]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "type": "string",
                "description": "Definition of Language and Region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US')."
            }
        }
    },
    "required": [
        "function"
    ]
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/CheckBindingEx.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "CheckBindingEx.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "CheckBindingEx",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "CheckBindingEx",
        "description": "Checks if a specific symbol is bound to a control attribute.",
        "category": "Binding",
        "returnValue": {
            "type": "tchmi:general#/definitions/Boolean",
            "description": "Result of the Access."
        },
        "arguments": [
            {
                "name": "control",
                "displayName": "control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "propertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "The target attribute property name of control.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            },
            {
                "name": "symbol",
                "displayName": "symbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "The target symbol.",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/TrimToLength.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "TrimToLength.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "TrimToLength",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "TrimToLength",
        "visible": true,
        "description": "Trims a string (from left or right side) to a specific length.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/String",
                "description": "Value to be trimmed",
                "required": true,
                "bindable": true
            },
            {
                "name": "trimToLength",
                "displayName": "trimToLength",
                "type": "tchmi:general#/definitions/Number",
                "description": "Target length of the String. Negative values trims from left side",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/GaugeValueFormatter.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "GaugeValueFormatter.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GaugeValueFormatter",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GaugeValueFormatter",
        "visible": true,
        "description": "Return a formatted string for the value passed in.",
        "category": "Formatting",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "value",
                "type": "tchmi:general#/definitions/Number",
                "description": "The value to format.",
                "required": true,
                "bindable": true
            },
            {
                "name": "maxDecimals",
                "displayName": "maxDecimals",
                "type": "tchmi:general#/definitions/Number",
                "description": "How many decimal places the value should have.",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": []
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/Decrement.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "Decrement.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Decrement",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Decrement",
        "visible": true,
        "description": "Decrement a binding value.",
        "category": "Data Conversion",
        "injectContextObject": true,
        "waitMode": "Asynchronous",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "value",
                "displayName": "value",
                "type": "tchmi:framework#/definitions/TcHmi.Functions.Beckhoff.Decrement.DecrementValueSymbol",
                "description": "Value to be decremented",
                "required": true,
                "bindable": true
            },
            {
                "name": "minValue",
                "displayName": "minValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "Minimum value(inclusive) to which the symbol will decremented",
                "required": false,
                "bindable": true
            },
            {
                "name": "stepWidth",
                "displayName": "stepWidth",
                "type": "tchmi:general#/definitions/Number",
                "description": "Used stepwidth for decrement",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": [
        {
            "schema": "Schema/Types.Schema.json"
        }
    ]
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/GetTheme.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "GetTheme.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GetTheme",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GetTheme",
        "description": "Gets the current Themename.",
        "category": "Theme",
        "returnValue": {
            "type": "tchmi:framework#/definitions/ThemeName"
        },
        "arguments": []
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/ConvertBooleanToVisibility.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "ConvertBooleanToVisibility.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ConvertBooleanToVisibility",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ConvertBooleanToVisibility",
        "visible": true,
        "description": "Converts boolean values to visibility enumeration values.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:framework#/definitions/Visibility"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "value",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            },
            {
                "name": "FalseValue",
                "displayName": "FalseValue",
                "type": "tchmi:framework#/definitions/Visibility",
                "description": "VisibilityValue if source value is false",
                "required": false,
                "bindable": true
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/CheckAccess.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "CheckAccess.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "CheckAccess",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "CheckAccess",
        "description": "Checks if an right is allowed for the current user on a control or its parents.",
        "category": "UserManagement",
        "returnValue": {
            "type": "tchmi:general#/definitions/Boolean",
            "description": "Result of the Access."
        },
        "arguments": [
            {
                "name": "tchmicontrol",
                "displayName": "TcHmiControl",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control to check the AccessRight on it.",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "AccessRightToCheck",
                "displayName": "AccessRightToCheck",
                "type": "tchmi:framework#/definitions/ControlAccessRightName",
                "description": "Name of an AccessRight to check.",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}

=== benhar-dev/ads-xbox-controller/src/twincat/Packages/Beckhoff.TwinCAT.HMI.Functions.12.750.1/runtimes/native1.12-tchmi/ToLowerCase.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "1.12.750.1",
        "major": 1,
        "minor": 12,
        "build": 750,
        "revision": 1
    },
    "dependencyFiles": [
        {
            "name": "ToLowerCase.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ToLowerCase",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ToLowerCase",
        "visible": true,
        "description": "Converts string value to lowercase.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/String",
                "description": "Value to lowercase",
                "required": true,
                "bindable": true
            }
        ]
    }
}
